name-template: "Version $NEXT_MINOR_VERSION"
tag-template: "v.$NEXT_MINOR_VERSION"

categories:
  - title: "🚀 New features"
    labels:
      - "enhancement"
  - title: "♻ Reworks"
    labels:
      - "rework"
  - title: "🔧 Fixed bugs"
    labels:
      - "bugfix"
  - title: "🕸 Staled Issues & PRs | Wont fix"
    labels:
      - "stale"
      - "wontfix"
  - title: "🐞 Known bugs"
    labels:
      - "bugs"
  - title: "🔨 Dependencies updates"
    labels:
      - "dependencies"
  - title: "📝 Other"
    labels:
      - "documentation"
      - "questions"
      - "other"

prerelease: true
sort-by: "title"

template: |
  ## ➕ Changes
  
  $CHANGES
  
  ## ✔ Contributors
  
  $CONTRIBUTORS
