name-template: "Version $NEXT_MINOR_VERSION"
tag-template: "Version $NEXT_MINOR_VERSION"

categories:
  - title: "🚀 New features"
    labels:
      - "enhancement"
  - title: "♻ Reworks"
    labels:
      - "rework"
  - title: "🔧 Fixed bugs"
    labels:
      - "bugfix"
  - title: "🐞 known bugs"
    labels:
      - "bugs"
  - title: "📝 Documentations and questions"
    labels:
      - "documentation"
      - "questions"
  - title: "🔨 Dependencies updates"
    labels:
      - "dependencies"
template: |

  $CHANGES
